mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*Mapper.xml

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
      url: jdbc:h2:tcp://localhost/~/spring_security;DATABASE_TO_UPPER=false;SCHEMA=SPRING_SECURITY
      driver-class-name: org.h2.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      username: sa
      password: foobar

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh